apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ace-pipelinerun-
  namespace: henda
spec:
  params:
  - name: app-name
    value: hello-world
  - name: git-url
    value: 'https://github.com/hindos/HelloWorld.git'
  - name: git-revision
    value: master
  - name: app-namespace
    value: henda
  - name: configurations
    value: ""
  - name: private-lan-id
    value: ""
  - name: private-ip
    value: ""
  - name: min-cpu
    value: "125m"
  - name: max-cpu
    value: "1000m"
  - name: min-memory
    value: "512Mi"
  - name: max-memory
    value: "2048Mi"
  - name: environment
    value: "dev"
  pipelineRef:
    name: new-ace-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
