apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2021-04-19T21:03:57Z'
  generation: 3
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:tasks': {}
      manager: Mozilla
      operation: Update
      time: '2021-04-19T21:10:19Z'
  name: new-ace-pipeline
  namespace: henda
  resourceVersion: '36575757'
  selfLink: /apis/tekton.dev/v1beta1/namespaces/henda/pipelines/new-ace-pipeline
  uid: 7ad024d0-5b68-4439-8afb-d058a1488e09
spec:
  params:
    - default: ''
      description: The url for the git repository
      name: git-url
      type: string
    - default: master
      description: 'The git revision (branch, tag, or sha) that should be built'
      name: git-revision
      type: string
    - default: integrationserver
      description: The integration server deployment name
      name: app-name
      type: string
    - default: default
      name: app-namespace
      type: string
    - default: ' '
      description: IntegrationServer configurations list (comma separated)
      name: configurations
      type: string
    - default: 250m
      description: Minimum CPU request
      name: min-cpu
      type: string
    - default: 500m
      description: Maximum CPU request
      name: max-cpu
      type: string
    - default: 256Mi
      description: Minimum memory request
      name: min-memory
      type: string
    - default: 512Mi
      description: Maximum memory request
      name: max-memory
      type: string
    - default: ''
      description: Dedicated worker node label
      name: worker-node
      type: string
    - default: ''
      description: Adds a new service selector label
      name: match-selector
      type: string
    - default: ''
      description: Private LAN ID of OpenShift Cluster
      name: private-lan-id
      type: string
    - default: ''
      description: Private IP Address of Service
      name: private-ip
      type: string
    - default: '1'
      description: Number of replicas to run
      name: replicas
      type: string
    - default: dev
      description: Deployment environment
      name: environment
      type: string
    - default: 'false'
      description: true if other images will reference this image
      name: master-image
      type: string
  tasks:
    - name: setup
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: app-namespace
          value: $(params.app-namespace)
        - name: environment
          value: $(params.environment)
      taskRef:
        kind: Task
        name: generic-setup
    - name: build
      params:
        - name: git-url
          value: $(tasks.setup.results.git-url)
        - name: git-revision
          value: $(tasks.setup.results.git-revision)
        - name: source-dir
          value: $(tasks.setup.results.source-dir)
        - name: tools-image
          value: $(tasks.setup.results.tools-image)
        - name: image-name
          value: $(tasks.setup.results.image-name)
        - name: image-tag
          value: $(tasks.setup.results.image-tag)
        - name: registry-location
          value: $(tasks.setup.results.registry-location)
        - name: registry-namespace
          value: $(tasks.setup.results.registry-namespace)
        - name: master-image
          value: $(params.master-image)
      runAfter:
        - setup
      taskRef:
        kind: Task
        name: generic-build
    - name: deploy
      params:
        - name: git-url
          value: $(tasks.setup.results.git-url)
        - name: git-revision
          value: $(tasks.setup.results.git-revision)
        - name: source-dir
          value: $(tasks.setup.results.source-dir)
        - name: image-name
          value: $(tasks.setup.results.image-name)
        - name: image-tag
          value: $(tasks.setup.results.image-tag)
        - name: registry-location
          value: $(tasks.setup.results.registry-location)
        - name: registry-namespace
          value: $(tasks.setup.results.registry-namespace)
        - name: app-namespace
          value: $(tasks.setup.results.app-namespace)
        - name: app-name
          value: $(params.app-name)
        - name: tools-image
          value: $(tasks.setup.results.tools-image)
        - name: api-server
          value: $(tasks.setup.results.api-server)
        - name: private-lan-id
          value: $(params.private-lan-id)
        - name: private-ip
          value: $(params.private-ip)
        - name: configurations
          value: $(params.configurations)
        - name: min-cpu
          value: $(params.min-cpu)
        - name: max-cpu
          value: $(params.max-cpu)
        - name: min-memory
          value: $(params.min-memory)
        - name: max-memory
          value: $(params.max-memory)
        - name: worker-node
          value: $(params.worker-node)
        - name: replicas
          value: $(params.replicas)
      runAfter:
        - build
      taskRef:
        kind: Task
        name: ace-deploy
